//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProsysMobile.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProsysMobile.Resources.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        internal static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Basket.
        /// </summary>
        internal static string AddBasket {
            get {
                return ResourceManager.GetString("AddBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add items you want to shop.
        /// </summary>
        internal static string AddItemsYouWantToShop {
            get {
                return ResourceManager.GetString("AddItemsYouWantToShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the quantity!.
        /// </summary>
        internal static string AnError0ccurredWhileUpdatingTheQuantity {
            get {
                return ResourceManager.GetString("AnError0ccurredWhileUpdatingTheQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred!.
        /// </summary>
        internal static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the product from the basket!.
        /// </summary>
        internal static string AnErrorOccurredWhileDeletingTheProductFromTheBasket {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileDeletingTheProductFromTheBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the user!.
        /// </summary>
        internal static string AnErrorOccurredWhileDeletingTheUser {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileDeletingTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching categories!.
        /// </summary>
        internal static string AnErrorOccurredWhileFetchingCategories {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileFetchingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching product details!.
        /// </summary>
        internal static string AnErrorOccurredWhileFetchingProductDetails {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileFetchingProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching the basket detail!.
        /// </summary>
        internal static string AnErrorOccurredWhileFetchingTheBasketDetail {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileFetchingTheBasketDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching the products!.
        /// </summary>
        internal static string AnErrorOccurredWhileFetchingTheProducts {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileFetchingTheProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Basket.
        /// </summary>
        internal static string ApplyBasket {
            get {
                return ResourceManager.GetString("ApplyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the account?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteTheAccount {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteTheAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string AreYouSureYouWantToLogOut {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        internal static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket Confirmed!.
        /// </summary>
        internal static string BasketConfirmed {
            get {
                return ResourceManager.GetString("BasketConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket Not Confirmed!.
        /// </summary>
        internal static string BasketNotConfirmed {
            get {
                return ResourceManager.GetString("BasketNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change List Design.
        /// </summary>
        internal static string ChangeListDesign {
            get {
                return ResourceManager.GetString("ChangeListDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code.
        /// </summary>
        internal static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals.
        /// </summary>
        internal static string Deals {
            get {
                return ResourceManager.GetString("Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string DontHaveAnAccount {
            get {
                return ResourceManager.GetString("DontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double View.
        /// </summary>
        internal static string DoubleView {
            get {
                return ResourceManager.GetString("DoubleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Total.
        /// </summary>
        internal static string GrossTotal {
            get {
                return ResourceManager.GetString("GrossTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Detail.
        /// </summary>
        internal static string ImageDetail {
            get {
                return ResourceManager.GetString("ImageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quantity!.
        /// </summary>
        internal static string InvalidQuantity {
            get {
                return ResourceManager.GetString("InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Detail.
        /// </summary>
        internal static string ItemDetail {
            get {
                return ResourceManager.GetString("ItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Total.
        /// </summary>
        internal static string NetTotal {
            get {
                return ResourceManager.GetString("NetTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ITEMS IN BASKET.
        /// </summary>
        internal static string NoItemsInBasket_U {
            get {
                return ResourceManager.GetString("NoItemsInBasket_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ITEMS IN FAVORITE.
        /// </summary>
        internal static string NoItemsInFavorite_U {
            get {
                return ResourceManager.GetString("NoItemsInFavorite_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Picture View.
        /// </summary>
        internal static string NoPictureView {
            get {
                return ResourceManager.GetString("NoPictureView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Amount.
        /// </summary>
        internal static string OrderAmount {
            get {
                return ResourceManager.GetString("OrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Detail.
        /// </summary>
        internal static string OrderDetail {
            get {
                return ResourceManager.GetString("OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection!.
        /// </summary>
        internal static string PleaseCheckYourInternetConnection {
            get {
                return ResourceManager.GetString("PleaseCheckYourInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the company code!.
        /// </summary>
        internal static string PleaseWriteTheCompanyCode {
            get {
                return ResourceManager.GetString("PleaseWriteTheCompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your email address!.
        /// </summary>
        internal static string PleaseWriteYourEMailAddress {
            get {
                return ResourceManager.GetString("PleaseWriteYourEMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your name!.
        /// </summary>
        internal static string PleaseWriteYourName {
            get {
                return ResourceManager.GetString("PleaseWriteYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your password!.
        /// </summary>
        internal static string PleaseWriteYourPassword {
            get {
                return ResourceManager.GetString("PleaseWriteYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your surname!.
        /// </summary>
        internal static string PleaseWriteYourSurname {
            get {
                return ResourceManager.GetString("PleaseWriteYourSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your favorite items here.
        /// </summary>
        internal static string SaveYourFavoriteItemsHere {
            get {
                return ResourceManager.GetString("SaveYourFavoriteItemsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here.
        /// </summary>
        internal static string SearchHere {
            get {
                return ResourceManager.GetString("SearchHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single View.
        /// </summary>
        internal static string SingleView {
            get {
                return ResourceManager.GetString("SingleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold out.
        /// </summary>
        internal static string SoldOut {
            get {
                return ResourceManager.GetString("SoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START SHOPPING.
        /// </summary>
        internal static string StartShopping_U {
            get {
                return ResourceManager.GetString("StartShopping_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store is closed for maintenance, please try again between @xxx..
        /// </summary>
        internal static string StoreMaintenanceWorkPleaseClosedDueToXxxAgainBetweenHoursTry {
            get {
                return ResourceManager.GetString("StoreMaintenanceWorkPleaseClosedDueToXxxAgainBetweenHoursTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product could not be added to favorites!.
        /// </summary>
        internal static string TheProductCouldNotBeAddedToFavorites {
            get {
                return ResourceManager.GetString("TheProductCouldNotBeAddedToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product could not be added to the basket!.
        /// </summary>
        internal static string TheProductCouldNotBeAddedToTheBasket {
            get {
                return ResourceManager.GetString("TheProductCouldNotBeAddedToTheBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product has been added to the basket!.
        /// </summary>
        internal static string TheProductHasBeenAddedToTheBasket {
            get {
                return ResourceManager.GetString("TheProductHasBeenAddedToTheBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity could not be updated because you have reached the maximum purchase quantity!.
        /// </summary>
        internal static string TheQuantityCouldNotBeUpdatedBecauseYouHaveReachedTheMaximumPurchaseQuantity {
            get {
                return ResourceManager.GetString("TheQuantityCouldNotBeUpdatedBecauseYouHaveReachedTheMaximumPurchaseQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no products in stock!.
        /// </summary>
        internal static string ThereAreNoProductsInStock {
            get {
                return ResourceManager.GetString("ThereAreNoProductsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register, please fill in the information..
        /// </summary>
        internal static string ToRegisterPleaseFillInTheInformation {
            get {
                return ResourceManager.GetString("ToRegisterPleaseFillInTheInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Total.
        /// </summary>
        internal static string VATTotal {
            get {
                return ResourceManager.GetString("VATTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string Warning_U {
            get {
                return ResourceManager.GetString("Warning_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yaso.
        /// </summary>
        internal static string yaso {
            get {
                return ResourceManager.GetString("yaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are below the minimum order amount!.
        /// </summary>
        internal static string YouAreBelowTheMinimumOrderAmount {
            get {
                return ResourceManager.GetString("YouAreBelowTheMinimumOrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the maximum purchase quantity!.
        /// </summary>
        internal static string YouHaveExceededTheMaximumPurchaseQuantity {
            get {
                return ResourceManager.GetString("YouHaveExceededTheMaximumPurchaseQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email or password is incorrect!.
        /// </summary>
        internal static string YourEmailOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("YourEmailOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been successfully received, you can continue shopping..
        /// </summary>
        internal static string YourOrderHasBeenSuccessfullyReceivedYouCanContinueShopping {
            get {
                return ResourceManager.GetString("YourOrderHasBeenSuccessfullyReceivedYouCanContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been sent!.
        /// </summary>
        internal static string YourRequestHasBeenSent {
            get {
                return ResourceManager.GetString("YourRequestHasBeenSent", resourceCulture);
            }
        }
    }
}
