//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProsysMobile.Resources.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ProsysMobile.Resources.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string yaso {
            get {
                return ResourceManager.GetString("yaso", resourceCulture);
            }
        }
        
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        internal static string Deals {
            get {
                return ResourceManager.GetString("Deals", resourceCulture);
            }
        }
        
        internal static string ItemDetail {
            get {
                return ResourceManager.GetString("ItemDetail", resourceCulture);
            }
        }
        
        internal static string AddBasket {
            get {
                return ResourceManager.GetString("AddBasket", resourceCulture);
            }
        }
        
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        internal static string SearchHere {
            get {
                return ResourceManager.GetString("SearchHere", resourceCulture);
            }
        }
        
        internal static string NoItemsInFavorite_U {
            get {
                return ResourceManager.GetString("NoItemsInFavorite_U", resourceCulture);
            }
        }
        
        internal static string SaveYourFavoriteItemsHere {
            get {
                return ResourceManager.GetString("SaveYourFavoriteItemsHere", resourceCulture);
            }
        }
        
        internal static string StartShopping_U {
            get {
                return ResourceManager.GetString("StartShopping_U", resourceCulture);
            }
        }
        
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        internal static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        internal static string NoItemsInBasket_U {
            get {
                return ResourceManager.GetString("NoItemsInBasket_U", resourceCulture);
            }
        }
        
        internal static string AddItemsYouWantToShop {
            get {
                return ResourceManager.GetString("AddItemsYouWantToShop", resourceCulture);
            }
        }
        
        internal static string GrossTotal {
            get {
                return ResourceManager.GetString("GrossTotal", resourceCulture);
            }
        }
        
        internal static string VATTotal {
            get {
                return ResourceManager.GetString("VATTotal", resourceCulture);
            }
        }
        
        internal static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        internal static string NetTotal {
            get {
                return ResourceManager.GetString("NetTotal", resourceCulture);
            }
        }
        
        internal static string ApplyBasket {
            get {
                return ResourceManager.GetString("ApplyBasket", resourceCulture);
            }
        }
        
        internal static string ImageDetail {
            get {
                return ResourceManager.GetString("ImageDetail", resourceCulture);
            }
        }
        
        internal static string ChangeListDesign {
            get {
                return ResourceManager.GetString("ChangeListDesign", resourceCulture);
            }
        }
        
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        internal static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string ToRegisterPleaseFillInTheInformation {
            get {
                return ResourceManager.GetString("ToRegisterPleaseFillInTheInformation", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        internal static string DontHaveAnAccount {
            get {
                return ResourceManager.GetString("DontHaveAnAccount", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string InvalidQuantity {
            get {
                return ResourceManager.GetString("InvalidQuantity", resourceCulture);
            }
        }
        
        internal static string TheProductHasBeenAddedToTheBasket {
            get {
                return ResourceManager.GetString("TheProductHasBeenAddedToTheBasket", resourceCulture);
            }
        }
        
        internal static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        internal static string TheProductCouldNotBeAddedToTheBasket {
            get {
                return ResourceManager.GetString("TheProductCouldNotBeAddedToTheBasket", resourceCulture);
            }
        }
        
        internal static string TheProductCouldNotBeAddedToFavorites {
            get {
                return ResourceManager.GetString("TheProductCouldNotBeAddedToFavorites", resourceCulture);
            }
        }
        
        internal static string AnErrorOccurredWhileFetchingProductDetails {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileFetchingProductDetails", resourceCulture);
            }
        }
        
        internal static string OrderAmount {
            get {
                return ResourceManager.GetString("OrderAmount", resourceCulture);
            }
        }
        
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Warning_U {
            get {
                return ResourceManager.GetString("Warning_U", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string AreYouSureYouWantToLogOut {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToLogOut", resourceCulture);
            }
        }
        
        internal static string AreYouSureYouWantToDeleteTheAccount {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteTheAccount", resourceCulture);
            }
        }
        
        internal static string AnErrorOccurredWhileDeletingTheUser {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileDeletingTheUser", resourceCulture);
            }
        }
        
        internal static string AnErrorOccurredWhileFetchingTheProducts {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileFetchingTheProducts", resourceCulture);
            }
        }
        
        internal static string AnErrorOccurredWhileFetchingCategories {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileFetchingCategories", resourceCulture);
            }
        }
        
        internal static string AnErrorOccurredWhileDeletingTheProductFromTheBasket {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileDeletingTheProductFromTheBasket", resourceCulture);
            }
        }
        
        internal static string OrderDetail {
            get {
                return ResourceManager.GetString("OrderDetail", resourceCulture);
            }
        }
        
        internal static string BasketConfirmed {
            get {
                return ResourceManager.GetString("BasketConfirmed", resourceCulture);
            }
        }
        
        internal static string BasketNotConfirmed {
            get {
                return ResourceManager.GetString("BasketNotConfirmed", resourceCulture);
            }
        }
        
        internal static string AnErrorOccurredWhileFetchingTheBasketDetail {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileFetchingTheBasketDetail", resourceCulture);
            }
        }
        
        internal static string SingleView {
            get {
                return ResourceManager.GetString("SingleView", resourceCulture);
            }
        }
        
        internal static string DoubleView {
            get {
                return ResourceManager.GetString("DoubleView", resourceCulture);
            }
        }
        
        internal static string NoPictureView {
            get {
                return ResourceManager.GetString("NoPictureView", resourceCulture);
            }
        }
        
        internal static string PleaseCheckYourInternetConnection {
            get {
                return ResourceManager.GetString("PleaseCheckYourInternetConnection", resourceCulture);
            }
        }
        
        internal static string PleaseWriteYourName {
            get {
                return ResourceManager.GetString("PleaseWriteYourName", resourceCulture);
            }
        }
        
        internal static string PleaseWriteYourSurname {
            get {
                return ResourceManager.GetString("PleaseWriteYourSurname", resourceCulture);
            }
        }
        
        internal static string PleaseWriteYourEMailAddress {
            get {
                return ResourceManager.GetString("PleaseWriteYourEMailAddress", resourceCulture);
            }
        }
        
        internal static string PleaseWriteTheCompanyCode {
            get {
                return ResourceManager.GetString("PleaseWriteTheCompanyCode", resourceCulture);
            }
        }
        
        internal static string YourRequestHasBeenSent {
            get {
                return ResourceManager.GetString("YourRequestHasBeenSent", resourceCulture);
            }
        }
        
        internal static string PleaseWriteYourPassword {
            get {
                return ResourceManager.GetString("PleaseWriteYourPassword", resourceCulture);
            }
        }
        
        internal static string YourEmailOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("YourEmailOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        internal static string AnError0ccurredWhileUpdatingTheQuantity {
            get {
                return ResourceManager.GetString("AnError0ccurredWhileUpdatingTheQuantity", resourceCulture);
            }
        }
        
        internal static string YourOrderHasBeenSuccessfullyReceivedYouCanContinueShopping {
            get {
                return ResourceManager.GetString("YourOrderHasBeenSuccessfullyReceivedYouCanContinueShopping", resourceCulture);
            }
        }
        
        internal static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        internal static string SoldOut {
            get {
                return ResourceManager.GetString("SoldOut", resourceCulture);
            }
        }
        
        internal static string ThereAreNoProductsInStock {
            get {
                return ResourceManager.GetString("ThereAreNoProductsInStock", resourceCulture);
            }
        }
        
        internal static string YouHaveExceededTheMaximumPurchaseQuantity {
            get {
                return ResourceManager.GetString("YouHaveExceededTheMaximumPurchaseQuantity", resourceCulture);
            }
        }
        
        internal static string TheQuantityCouldNotBeUpdatedBecauseYouHaveReachedTheMaximumPurchaseQuantity {
            get {
                return ResourceManager.GetString("TheQuantityCouldNotBeUpdatedBecauseYouHaveReachedTheMaximumPurchaseQuantity", resourceCulture);
            }
        }
        
        internal static string StoreMaintenanceWorkPleaseClosedDueToXxxAgainBetweenHoursTry {
            get {
                return ResourceManager.GetString("StoreMaintenanceWorkPleaseClosedDueToXxxAgainBetweenHoursTry", resourceCulture);
            }
        }
        
        internal static string YouAreBelowTheMinimumOrderAmount {
            get {
                return ResourceManager.GetString("YouAreBelowTheMinimumOrderAmount", resourceCulture);
            }
        }
    }
}
